using System.ComponentModel.DataAnnotations;

namespace HabitTracker.Models
{
    public class SavingsGoal
    {
        public int Id { get; set; }

        [Required]
        public int UserId { get; set; }

        [Required, MaxLength(120)]
        public string Name { get; set; } = string.Empty;

        public decimal TargetAmount { get; set; }
        public decimal StartingAmount { get; set; }

        // Savings generated by habits while this goal was active are accumulated here.
        // SavingsBaselineAtActivation lets the service calculate the live delta without
        // duplicating money across goals when users switch the active goal.
        public decimal AccumulatedHabitSavings { get; set; }
        public decimal SavingsBaselineAtActivation { get; set; }

        public bool IsActive { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? TargetDate { get; set; }

        public User User { get; set; } = null!;
    }
}
