// <auto-generated />
using System;
using HabitTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808204711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Habits_UserId");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "purple",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stay hydrated throughout the day",
                            Icon = "🎯",
                            TargetType = "Daily",
                            Title = "Drink 8 Glasses of Water",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "purple",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Read a book or article",
                            Icon = "🎯",
                            TargetType = "Daily",
                            Title = "Read for 30 Minutes",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "purple",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gym, run, or home workout",
                            Icon = "🎯",
                            TargetType = "Weekly",
                            Title = "Exercise 3x Per Week",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HabitTracker.Models.HabitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HabitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_HabitLogs_Date");

                    b.HasIndex("HabitId", "Date")
                        .IsUnique()
                        .HasDatabaseName("IX_HabitLogs_HabitId_Date");

                    b.ToTable("HabitLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true,
                            Date = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 2,
                            Completed = false,
                            Date = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 3,
                            Completed = true,
                            Date = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 4,
                            Completed = true,
                            Date = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 5,
                            Completed = false,
                            Date = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 6,
                            Completed = true,
                            Date = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 7,
                            Completed = true,
                            Date = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 1
                        },
                        new
                        {
                            Id = 8,
                            Completed = true,
                            Date = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 9,
                            Completed = true,
                            Date = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 10,
                            Completed = true,
                            Date = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 11,
                            Completed = true,
                            Date = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 12,
                            Completed = true,
                            Date = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 13,
                            Completed = true,
                            Date = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 14,
                            Completed = true,
                            Date = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 2
                        },
                        new
                        {
                            Id = 15,
                            Completed = false,
                            Date = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        },
                        new
                        {
                            Id = 16,
                            Completed = false,
                            Date = new DateTime(2026, 8, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        },
                        new
                        {
                            Id = 17,
                            Completed = true,
                            Date = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        },
                        new
                        {
                            Id = 18,
                            Completed = false,
                            Date = new DateTime(2026, 8, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        },
                        new
                        {
                            Id = 19,
                            Completed = false,
                            Date = new DateTime(2026, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        },
                        new
                        {
                            Id = 20,
                            Completed = true,
                            Date = new DateTime(2026, 8, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        },
                        new
                        {
                            Id = 21,
                            Completed = false,
                            Date = new DateTime(2026, 8, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HabitId = 3
                        });
                });

            modelBuilder.Entity("HabitTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@habittracker.com",
                            Name = "Demo User",
                            PasswordHash = "$2a$11$X3Vf8dGfQZqWvBbNnMmLlOoPpQqRrSsTtUuVvWwXxYyZz1234567"
                        });
                });

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.HasOne("HabitTracker.Models.User", "User")
                        .WithMany("Habits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HabitTracker.Models.HabitLog", b =>
                {
                    b.HasOne("HabitTracker.Models.Habit", "Habit")
                        .WithMany("HabitLogs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.Navigation("HabitLogs");
                });

            modelBuilder.Entity("HabitTracker.Models.User", b =>
                {
                    b.Navigation("Habits");
                });
#pragma warning restore 612, 618
        }
    }
}
